name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # อัปเดตเป็น v4 เพื่อรองรับ Node รุ่นใหม่
        with:
          fetch-depth: 0

      - name: Inject Commit Date
        run: |
          # ตั้งค่า Timezone เป็นกรุงเทพฯ และดึงเวลา Commit ล่าสุด
          COMMIT_DATE=$(TZ='Asia/Bangkok' git log -1 --format="%ad" --date=format:"%d/%m/%Y %H:%M")
          echo "Last Commit: $COMMIT_DATE"
          # ใช้ @ เป็นตัวคั่นใน sed เพื่อป้องกันปัญหาหากในตัวแปรมีเครื่องหมาย /
          sed -i "s@{{COMMIT_DATE}}@$COMMIT_DATE@g" index.html

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Hosting
        run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }} --project calcurrency-a1d74
